import type { Locale, MediaView } from './content';

export const ui = {
  en: {
    siteName: 'Panzonato',
    siteDescriptor: 'family history',
    skip: 'Skip to content',
    navLabel: 'Exhibition sections',
    nav: { chapters: 'The story', people: 'The people', archive: 'The archive', about: 'About' },
    language: 'Português',
    languageLabel: 'Read in Portuguese',
    preview: 'An exhibition in progress',
    footerLine: 'Italy · Brazil · generations',
    homeTitle: 'Family history exhibition',
    homeDescription: 'A family history told through places, people, photographs, and the traces that remain.',
    openingOverline: ['Italy · Brazil', 'Leaving · arriving · belonging'],
    openingTitle: 'Across an ocean.',
    openingEmphasis: 'Through generations.',
    openingIntro: 'From a parish near Venice to a new life in Brazil. Follow the Panzonato and Moro families through the records they left and the places that still hold their story.',
    begin: 'Begin the story',
    storyEyebrow: 'The story',
    storyTitle: 'One journey.',
    storyEmphasis: 'Many beginnings.',
    storyIntro: 'Five chapters follow a family story through departure, arrival, memory, and the evidence that connects them.',
    chapterGroup: 'Five story chapters',
    chapter: 'Chapter',
    selectedContext: 'Selected chapter context',
    readChapter: 'Read this chapter',
    readingEyebrow: 'A short reading',
    readingMeta: 'From chapter 02',
    readingTitle: 'The shape of a departure',
    readingLead: 'Before a journey can be remembered, it has to be lived as a series of ordinary decisions.',
    readingExcerpt: 'An ocean crossing is more than a line between two ports. It holds waiting, movement, uncertainty, and the first questions about what might come next. The surviving traces help locate that experience without filling its silences with invention.',
    readingLink: 'Continue the crossing',
    journeyLabel: 'Follow the journey',
    journeyHint: 'A place can open a story',
    stageGroup: 'Select a place in the story',
    stageCountries: { genoa: '01 / Italy', santos: '02 / Brazil', gambarare: '03 / Looking back' },
    stageNames: { genoa: 'Genoa', santos: 'Santos', gambarare: 'Gambarare' },
    stages: {
      genoa: { eyebrow: 'Departure', title: 'At the edge of another life.', copy: 'Begin with a port, and with the wider world through which the family story passes.' },
      santos: { eyebrow: 'Arrival', title: 'A shore is only the beginning.', copy: 'The story continues beyond the crossing, into the places where a new life takes shape.' },
      gambarare: { eyebrow: 'Looking back', title: 'The past has an address.', copy: 'Return to a place in the story and read a present-day photograph alongside the surviving records.' },
    },
    inspect: 'Inspect image',
    lookCloser: 'Look closer',
    peopleTitle: 'Names become lives.',
    peopleCopy: 'Parents, children, siblings, and the families they formed. Follow the connections from the Veneto to São Paulo.',
    meetPeople: 'Meet the people',
    archiveTitle: 'A closer look at the evidence.',
    archiveCopy: 'Parish registers, immigration records, nineteenth-century photographs, and return visits. Explore the collection behind the story.',
    exploreArchive: 'Explore the archive',
    loadingError: 'The image could not be loaded. The previous selection remains in view.',
    close: 'Close', zoom: 'Zoom', zoomImage: 'Zoom image', zoomOut: 'Zoom out', zoomIn: 'Zoom in', reset: 'Reset',
    scrollImage: 'Scrollable full image', sourceRecord: 'View source record', historicalContext: 'Photographic record',
    breadcrumbHome: 'Home', allChapters: 'All chapters', allPeople: 'All people', allSources: 'All sources',
    nextChapter: 'Next chapter', previousChapter: 'Previous chapter', onThisPage: 'On this page', relatedEvidence: 'Related evidence', relatedPeople: 'People in this chapter',
    chaptersTitle: 'The story', chaptersIntro: 'Five chapters bring places, people, and surviving traces into one unfolding account.',
    peopleIndexTitle: 'The people', peopleIndexIntro: 'A family stretches in many directions. Begin with a name, then follow the relationships, places, and records that connect one generation to the next.',
    profile: 'Profile', connectedChapters: 'Connected chapters', namesAlsoRecorded: 'Names also recorded as',
    archiveIndexTitle: 'The archive', archiveIndexIntro: 'A collection to wander through: handwritten names, ocean liners, coffee harvests, parish interiors. Each object opens another part of the story.',
    source: 'Source', repository: 'Repository', locator: 'Locator', citation: 'Citation', imageCredit: 'Image credit', rights: 'Rights and use', recordType: 'Record type',
    sourceKinds: { context: 'Historical context', field: 'Return visits', record: 'Family record', reference: 'Research & reading' },
    archiveSearch: 'Search names, places, subjects…', searchLabel: 'Search the archive', allRecords: 'Everything', results: 'records shown', noResults: 'No records match. Try another name or subject.',
    galleryTitle: 'A closer look', transcriptTitle: 'Read the record', evidenceNoteTitle: 'About this evidence', familyConnections: 'Family connections',
    generations: { roots: 'The Italian roots', crossing: 'The family who crossed', brazil: 'The next generation' },
    timelineTitle: 'A life is made of dates.', timelineEmphasis: 'History lives between them.', timelineIntro: 'Open a moment to meet the people and records behind it.', timelineEyebrow: 'Across the years', timelineSource: 'Read the source',
    archiveSelected: 'From the collection', archiveSelectedTitle: 'The details bring it to life.',
    breadcrumbLabel: 'Breadcrumb',
    aboutTitle: 'About this exhibition',
    aboutIntro: 'Panzonato is a bilingual, source-led family history exhibition in development.',
    aboutBody: [
      'The exhibition brings narrative chapters, people, places, and visual records together without asking the evidence to say more than it can support.',
      'The chapters draw on the family research archive: Italian and Brazilian records, immigration material, historical publications, and photographs made on return visits. Where records disagree, the source notes preserve the difference.',
      'Context photographs describe the worlds around the family story; they are not presented as family photographs unless a record explicitly establishes that connection.',
    ],
    fontCreditsTitle: 'Typography and font licences',
    fontCreditsIntro: 'The exhibition uses locally hosted Newsreader and DM Sans. Their licence texts are available here.',
    fontLicense: 'Open Font License',
    editionNotice: 'This edition is in progress. Some text and source information is provisional.',
  },
  'pt-br': {
    siteName: 'Panzonato',
    siteDescriptor: 'história de família',
    skip: 'Pular para o conteúdo',
    navLabel: 'Seções da exposição',
    nav: { chapters: 'A história', people: 'As pessoas', archive: 'O arquivo', about: 'Sobre' },
    language: 'English',
    languageLabel: 'Ler em inglês',
    preview: 'Uma exposição em construção',
    footerLine: 'Itália · Brasil · gerações',
    homeTitle: 'Exposição de história familiar',
    homeDescription: 'Uma história de família contada por lugares, pessoas, fotografias e pelos vestígios que permanecem.',
    openingOverline: ['Itália · Brasil', 'Partir · chegar · pertencer'],
    openingTitle: 'Através de um oceano.',
    openingEmphasis: 'Por gerações.',
    openingIntro: 'De uma paróquia perto de Veneza a uma nova vida no Brasil. Acompanhe as famílias Panzonato e Moro pelos registros que deixaram e pelos lugares que guardam sua história.',
    begin: 'Comece a história',
    storyEyebrow: 'A história',
    storyTitle: 'Uma viagem.',
    storyEmphasis: 'Muitos começos.',
    storyIntro: 'Cinco capítulos acompanham uma história familiar pela partida, chegada, memória e pelas evidências que as conectam.',
    chapterGroup: 'Cinco capítulos da história',
    chapter: 'Capítulo',
    selectedContext: 'Contexto do capítulo selecionado',
    readChapter: 'Leia este capítulo',
    readingEyebrow: 'Uma breve leitura',
    readingMeta: 'Do capítulo 02',
    readingTitle: 'A forma de uma partida',
    readingLead: 'Antes que uma viagem possa ser lembrada, ela precisa ser vivida como uma série de decisões cotidianas.',
    readingExcerpt: 'Uma travessia oceânica é mais do que uma linha entre dois portos. Ela contém espera, movimento, incerteza e as primeiras perguntas sobre o que virá depois. Os vestígios preservados ajudam a situar essa experiência sem preencher seus silêncios com invenção.',
    readingLink: 'Continue a travessia',
    journeyLabel: 'Acompanhe a viagem',
    journeyHint: 'Um lugar pode abrir uma história',
    stageGroup: 'Selecione um lugar da história',
    stageCountries: { genoa: '01 / Itália', santos: '02 / Brasil', gambarare: '03 / Revendo o passado' },
    stageNames: { genoa: 'Gênova', santos: 'Santos', gambarare: 'Gambarare' },
    stages: {
      genoa: { eyebrow: 'Partida', title: 'No limite de uma outra vida.', copy: 'Comece por um porto e pelo mundo mais amplo atravessado por esta história familiar.' },
      santos: { eyebrow: 'Chegada', title: 'A costa é apenas o começo.', copy: 'A história continua depois da travessia, nos lugares onde uma nova vida ganha forma.' },
      gambarare: { eyebrow: 'Revendo o passado', title: 'O passado tem um endereço.', copy: 'Volte a um lugar da história e leia uma fotografia atual junto aos registros que sobreviveram.' },
    },
    inspect: 'Examinar imagem',
    lookCloser: 'Olhar mais de perto',
    peopleTitle: 'Nomes se tornam vidas.',
    peopleCopy: 'Pais, filhos, irmãos e as famílias que formaram. Siga os laços do Vêneto a São Paulo.',
    meetPeople: 'Conheça as pessoas',
    archiveTitle: 'Um olhar atento às evidências.',
    archiveCopy: 'Registros paroquiais, documentos de imigração, fotografias do século XIX e viagens de retorno. Explore a coleção por trás da história.',
    exploreArchive: 'Explore o arquivo',
    loadingError: 'Não foi possível carregar a imagem. A seleção anterior continua visível.',
    close: 'Fechar', zoom: 'Ampliação', zoomImage: 'Ampliar imagem', zoomOut: 'Reduzir', zoomIn: 'Ampliar', reset: 'Restaurar',
    scrollImage: 'Imagem ampliada com rolagem', sourceRecord: 'Ver registro da fonte', historicalContext: 'Registro fotográfico',
    breadcrumbHome: 'Início', allChapters: 'Todos os capítulos', allPeople: 'Todas as pessoas', allSources: 'Todas as fontes',
    nextChapter: 'Próximo capítulo', previousChapter: 'Capítulo anterior', onThisPage: 'Nesta página', relatedEvidence: 'Evidências relacionadas', relatedPeople: 'Pessoas neste capítulo',
    chaptersTitle: 'A história', chaptersIntro: 'Cinco capítulos reúnem lugares, pessoas e vestígios em um relato que se desdobra.',
    peopleIndexTitle: 'As pessoas', peopleIndexIntro: 'Uma família se estende em muitas direções. Comece por um nome e siga os laços, lugares e registros que conectam uma geração à seguinte.',
    profile: 'Perfil', connectedChapters: 'Capítulos relacionados', namesAlsoRecorded: 'Nomes também registrados como',
    archiveIndexTitle: 'O arquivo', archiveIndexIntro: 'Uma coleção para explorar: nomes manuscritos, transatlânticos, colheitas de café, interiores de igrejas. Cada objeto abre outra parte da história.',
    source: 'Fonte', repository: 'Repositório', locator: 'Localizador', citation: 'Citação', imageCredit: 'Crédito da imagem', rights: 'Direitos e uso', recordType: 'Tipo de registro',
    sourceKinds: { context: 'Contexto histórico', field: 'Viagens de retorno', record: 'Registro familiar', reference: 'Pesquisa e leituras' },
    archiveSearch: 'Busque nomes, lugares, assuntos…', searchLabel: 'Buscar no arquivo', allRecords: 'Tudo', results: 'registros encontrados', noResults: 'Nenhum registro encontrado. Tente outro nome ou assunto.',
    galleryTitle: 'Um olhar mais próximo', transcriptTitle: 'Leia o registro', evidenceNoteTitle: 'Sobre esta evidência', familyConnections: 'Laços de família',
    generations: { roots: 'As raízes italianas', crossing: 'A família que atravessou', brazil: 'A geração seguinte' },
    timelineTitle: 'Uma vida é feita de datas.', timelineEmphasis: 'A história vive entre elas.', timelineIntro: 'Abra um momento para conhecer as pessoas e os registros por trás dele.', timelineEyebrow: 'Ao longo dos anos', timelineSource: 'Leia a fonte',
    archiveSelected: 'Da coleção', archiveSelectedTitle: 'Os detalhes dão vida à história.',
    breadcrumbLabel: 'Navegação estrutural',
    aboutTitle: 'Sobre esta exposição',
    aboutIntro: 'Panzonato é uma exposição bilíngue de história familiar, orientada por fontes e ainda em desenvolvimento.',
    aboutBody: [
      'A exposição aproxima capítulos narrativos, pessoas, lugares e registros visuais sem pedir que as evidências digam mais do que podem sustentar.',
      'Os capítulos se apoiam no arquivo de pesquisa familiar: registros italianos e brasileiros, documentos de imigração, publicações históricas e fotografias de viagens de retorno. Quando os registros divergem, as notas das fontes preservam a diferença.',
      'Fotografias de contexto descrevem os mundos ao redor da história familiar; elas não são apresentadas como fotografias da família sem que um registro estabeleça essa ligação.',
    ],
    fontCreditsTitle: 'Tipografia e licenças de fontes',
    fontCreditsIntro: 'A exposição usa Newsreader e DM Sans hospedadas localmente. Os textos das licenças estão disponíveis aqui.',
    fontLicense: 'Licença Open Font',
    editionNotice: 'Esta edição está em construção. Parte do texto e das informações de fonte é provisória.',
  },
} as const;

export type UIStrings = (typeof ui)[Locale];

export function strings(locale: Locale): UIStrings {
  return ui[locale];
}

export function safeJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
}

export function exhibitionPayload(
  locale: Locale,
  media: MediaView[],
  chapters: Array<{ number: string; title: string; copy: string; mediaId: string; href: string }> = [],
  stages: Record<string, { eyebrow: string; title: string; copy: string; mediaId: string }> = {},
) {
  const t = strings(locale);
  return {
    locale,
    labels: { chapter: t.chapter, inspect: t.inspect, loadingError: t.loadingError },
    media: Object.fromEntries(media.map((item) => [item.id, item])),
    chapters,
    stages,
  };
}
